### ISSUE TITLE
The running GLPI doesn't support uploading JPEG files

### ISSUE THREAD

**Issue by ghs-medilies** [medilies/glpi-docker#1]
```text
Uncaught Exception Error: Call to undefined function imagecreatefromjpeg() in /var/www/html/vendor/blueimp/jquery-file-upload/server/php/UploadHandler.php at line 612
```

**Potential solution:**
Fix the way GD extension is being added to the container
https://gist.github.com/shov/f34541feae29afedd93208df4bf428f3#file-dockerfile-L26

**Comment by medilies** [comment]
Fixed the installation of the GD extension in [This commit](https://github.com/medilies/glpi/commit/c4f4ff6084809ae01d870602c3ccbc63392e482c) `glpi/dockerfile line28`


Refs:
https://stackoverflow.com/questions/47292221/troubles-with-docker-php7-gd-resulting-in-call-to-undefined-function-imagec
https://www.php.net/manual/en/image.installation.php
